name: post

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: post
      run: ./post.sh
      env:
        email: ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
